#Example configuration file, remember to remove "example_"!
#For getting a discord token: https://discord.com/developers/applications

#Bot token, get one from https://discord.com/developers/applications
token: ""

#Level of logging
loglevel: "informational"

# Voice used to generate audio files
voice: "Roberto"

# REST endpoint for Roberto voice synthesis
restroberto: "http://localhost:8087/audio"

# Token for REST endpoint authentication
restrobertotoken: "token1"